spring.application.name=macroflow
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.gqbaununtewkszmhanvu
spring.datasource.password=Bmo89PkZMV0RCcra

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=qaMJrFKsRoBWCOPT9v89RX3qbooVDuro5AiIWLHknnBopLX0uw6uniFtZQ3hpMWL
resend.api.key=re_Ko2dqkVh_KaNDptA31nN7eiuyLsEoXWJW
groq.api.key=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
server.port=${PORT:8080}