spring.application.name=macroflow
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=macroflow.oficial@gmail.com
spring.mail.password=grdc rmrl ztpc bdff
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true