spring.application.name=macroflow
spring.datasource.url=jdbc:postgresql://ep-lingering-bird-acc8atpz-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OKILixM3WzT7

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=qaMJrFKsRoBWCOPT9v89RX3qbooVDuro5AiIWLHknnBopLX0uw6uniFtZQ3hpMWL
resend.api.key=re_9afjrUMU_4NxwJVo3XPCSdcRkdSzm2P8E
groq.api.key=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
server.port=${PORT:8080}